version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: unique-random-array
    versions:
    - 3.0.0
  - dependency-name: p-reflect
    versions:
    - 3.0.0
  - dependency-name: mimic-fn
    versions:
    - 4.0.0
  - dependency-name: p-timeout
    versions:
    - 5.0.0
  - dependency-name: prism-themes
    versions:
    - 1.6.0
  - dependency-name: p-retry
    versions:
    - 4.4.0
  - dependency-name: puppeteer-core
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
